### ISSUE TITLE
Joystick Control

### ISSUE THREAD

**Issue by aminmahmoam** [DIT113-V22/group-10#39] opened 2022-04-25 09:43 UTC
As a user, I want to be able to control the car with joystick so that I can have a more pleasant experience with navigating the car.

Acceptance criteria:
The car can be controlled by the joystick.

**Comment by YasaminFazeli** [comment] 2022-05-02 08:53
The acceptance criteria are satisfied and the commits have been merged with the master branch so the issue is closed.

**Closed by YasaminFazeli** 2022-05-02 08:53 UTC
Labels: Sprint#2
